SmartGridready/SGrSpecifications

SchemaDatabase/SGr/Generic/BaseType_FunctionalProfileCategory.xsd, XMLInstances/ExtInterfaces/MEO_EI_Propilot_V0.0.1.xml, XMLInstances/ExtInterfaces/SGr_04_0005_xxxx_GARO_WallboxV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0014_0000_WAGO_SmartMeterV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0016_xxxx_ABBMeterV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0018_CLEMAP_EIcloudEnergyMonitorV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0034_0053_SCC_SubMeterElectricity_v0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_CLEMAPEnergyMonitorEIV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_WallboxAsymV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_WallboxV0.2.1.xml, XMLInstances/ExtInterfaces/abb_terra_01.xml, XMLInstances/FuncProfiles/FP_0_0011_13_4_0.2_ActiveEnergyBalanceAC.xml, XMLInstances/FuncProfiles/FP_0_0011_19_4_0.2_VoltageDC.xml, XMLInstances/FuncProfiles/FP_0_0011_20_4_0.2_CurrentDC.xml, XMLInstances/FuncProfiles/FP_0_0011_2_4_0.2_ReactiveEnergyAC.xml, XMLInstances/FuncProfiles/FP_0_0011_3_4_0.2_ApparentEnergyAC.xml, XMLInstances/FuncProfiles/FP_0_0011_6_4_0.2_ApparentPowerAC.xml, XMLInstances/FuncProfiles/FP_0_0011_7_4_0.2_VoltageAC.xml, XMLInstances/FuncProfiles/FP_0_0011_9_4_0.2_PowerFactor.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_ActiveEnergyAC_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_ActivePowerAC_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_CurrentAC_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_Frequency_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_ReactivePowerAC_m_1.0.xml, XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/DeviceFrame.xsl, XMLInstances/xsl/FunctionalProfileFrame.xsl
Rename NonSpecific to Metering
=> #160 Rename NonSpecific to Metering

XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_1_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_2m_1.0.xml, XMLInstances/xsl/DeviceFrame.xsl, XMLInstances/xsl/FunctionalProfileFrame.xsl, XMLInstances/xsl/SGr.css
Fix Footnote Display on Printout
=> #167 Fix Footnote Display on Printout

SchemaDatabase/SGr/Generic/BaseTypes.xsd, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_1_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_2m_1.0.xml, XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/FunctionalProfile.xsl, XMLInstances/xsl/FunctionalProfileFrame.xsl, XMLInstances/xsl/GenericAttributes.xsl, XMLInstances/xsl/Helpers.xsl
=> #150 Fixes for XSL

XMLInstances/FuncProfiles/FP_SGr_EVSE_SGrStates_EVSE_2m_1.0.xml, XMLInstances/xsl/FunctionalProfileFrame.xsl
=> #150 new fixes for xsl

XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2m_1.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2m_1.1.xml, XMLInstances/xsl/GenericAttributes.xsl
=> #42 SGCP Finalization

XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2m_1.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2m_1.1.xml
=> #42 SGCP Finalization 2m

XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2m_1.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2m_1.1.xml
=> #42 SGCP Finalization 2m fixes

SchemaDatabase/SGr/Product/ModbusTypes.xsd
Fix Mapping of Modbus Booleans
=> Fix Mapping of Modbus Booleans

XMLInstances/xsl/TransportServiceModbus.xsl
=> #120 Fix ModbusTCP

XMLInstances/ExtInterfaces/SGr_02_mmmm_dddd_SwiSBox_Actuator.xml, XMLInstances/FuncProfiles/FP_SGr_Actuator_Relais_2m_0.1.xml
=> Swistec deklaration

XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/Helpers.xsl, XMLInstances/xsl/SGr.xsl
=> #150 Fixes for XSL and Firefox

SchemaDatabase/SGr/Product/RestApiTypes.xsd
=> #190 Fix RestAPI EmptyType

XMLInstances/xsl/DeviceFrame.xsl, XMLInstances/xsl/FunctionalProfileFrame.xsl
=> #208 Fix Sequence of Footnotes

XMLInstances/FuncProfiles/FP_SGr_EVSE_LoadReduction_EVSE_1_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_EVSE_LoadReduction_EVSE_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_EVSE_LoadReduction_EVSE_2m_1.0.xml
@ArndGerns please rebase
@ginoagb please review the 3 EVSE functional profiles
=> Evse review

XMLInstances/xsl/SGr.xsl
=> All Languages for EID

XMLInstances/ExtInterfaces/EI4_UniDirFlexFeedIn_3632Lv2.xml, XMLInstances/ExtInterfaces/EI4_UniDirFlexLoad_3631Lv2.xml, XMLInstances/ExtInterfaces/FullEi4Modbus_0_0036_0030_4_0.1_SGCP_BiDirFlexMgmt.xml, XMLInstances/GenericAttributes/MaximumRunRime.xml, XMLInstances/GenericAttributes/SmoothTransition.xml
=> #198 Fix Attributes again

XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2m_1.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2m_1.1.xml
=> English translation added

XMLInstances/ExtInterfaces/SGr_02_mmmm_8288089799_Smart-me_SubMeterElectricity_V0.0.0.xml, XMLInstances/ExtInterfaces/SGr_02_mmmm_8288089799_Smart-me_SubMeterElectricity_V1.0.0.xml
=> #240 Smart-me Declaration

XMLInstances/ExtInterfaces/SGr_02_4893879785_8288144069_SwiSBox_SubMeterElectricity_V1.0.0.xml
=> #242 Rename SwiSBox Version

XMLInstances/xsl/FunctionalProfileFrame.xsl
Display GenericAttributes only once
=> #245 Display GenericAttributes only once

XMLInstances/GenericAttributes/StabilityFallback.xml
fix generic attribute stability fallback
=> fix generic attribute stability fallback

XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_2m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_1_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_SG-ReadyStates_bwp_2_1.0.xml, XMLInstances/xsl/SGr.css, XMLInstances/xsl/SGr.xsl
TextChange Heatpump SG-ReadyStates_bwp
=> TextChange Heatpump SG-ReadyStates_bwp

XMLInstances/ExtInterfaces/SGr_02_mmmm_8288089799_Smart-me_SubMeterElectricity_V1.0.0.xml
Added username/password for RestAPI basic authentication.
Removed '* 1000' from JMES-path expression
Added unitConversionMultiplicator 0.001 (Wh to kWh)
=> Check and fix new functiontional profile for SmartMe meter.

SchemaDatabase/SGr/FunctionalProfile/FunctionalProfileFrame.xsd, SchemaDatabase/SGr/Generic/BaseTypes.xsd, SchemaDatabase/SGr/Generic/DataPoint.xsd, SchemaDatabase/SGr/Product/ModbusInterface.xsd, SchemaDatabase/SGr/Product/RestApiInterface.xsd, XMLInstances/ExtInterfaces/SGr_02_0018_CLEMAP_EIcloudEnergyMonitor_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_CLEMAPEnergyMonitorEIV0.2.1.xml, XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/DeviceFrame.xsl, XMLInstances/xsl/FunctionalProfileFrame.xsl
Add constant data points to Products
=> #252 Add constant data points to Products

XMLInstances/ExtInterfaces/SGr_02_mmmm_8288089799_Smart-me_SubMeterElectricity_V1.1.0.xml
Increase version of Smart-me EID
=> #249 Increase version of Smart-me EID

SchemaDatabase/SGr/Product/RestApiTypes.xsd, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_GroupeE_V0.0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_V0.0.1.xml, XMLInstances/FuncProfiles/FP_SGr_Dynamic_Tariff_0.1.xml
Added new EI-XML for Swisspower and GroupeE for their dynamic-tariff endpoints. 
Adapted documentation of FP and EI-definitions.
Removed obsolete elements from XML-schema definitions.
=> Adapt XML-Schema definitions for dynamic tariffs.

SchemaDatabase/SGr/Product/Product.xsd, XMLInstances/ExtInterfaces/SGr_02_0018_CLEMAP_EIcloudEnergyMonitor_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_CLEMAPEnergyMonitorEIV0.2.1.xml, XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/DeviceFrame.xsl, XMLInstances/xsl/Helpers.xsl
Add Description of Configuration Items to Product Definition
=> #258 Add Description of Configuration Items to Product Definition

XMLInstances/ExtInterfaces/SGr_02_0017_xxxx_HOVAL_HeatPump_V0.1.1.xml, XMLInstances/ExtInterfaces/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V0.5.1.xml
=> #265 FP HeatPumpControl Level 4

XMLInstances/ExtInterfaces/SGr_02_0018_CLEMAP_EIcloudEnergyMonitor_V1.0.0.xml
=> #258 Fix Configuration Definition

XMLInstances/ExtInterfaces/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V0.5.1.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_BufferStorageCtrl_4m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_EnergyMonitor_m_0.5.xml
=> #265 Corrections for Heatpump

XMLInstances/ExtInterfaces/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V0.5.1.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_BufferStorageCtrl_4m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_DomHotWaterCtrl_4m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_HeatCoolCtrl_4m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_PowerCtrl_4m_0.5.xml
Corrections for HeatPump Offsets
=> #265 Corrections for HeatPump Offsets

XMLInstances/xsl/SGr.css
XSL for Messaging Based Interfaces
=> XSL for Messaging Based Interfaces

XMLInstances/ExtInterfaces/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V0.5.1.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_DomHotWaterCtrl_4m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_HeatCoolCtrl_4m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_HeatPumpBase_4m_0.5.xml
=> #265 Cleanup Heat Pumps

XMLInstances/ExtInterfaces/SGr_04_0016_xxxx_ABBMeterV0.2.1.xml, XMLInstances/FuncProfiles/FP_0_0011_13_4_0.2_PowerQuadrant.xml, XMLInstances/FuncProfiles/FP_0_0011_13_4_0.2_ReactiveEnergyBalanceAC2.xml, XMLInstances/FuncProfiles/FP_0_0011_2_4_0.2_ReactiveEnergyAC.xml
Correct Unit for Current in ABB
=> Correct Unit for Current in ABB

XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_Eaton_ChargingStation_V0.5.3.xml
=> #254 Configuration for IP-Address

SchemaDatabase/SGr/Generic/DataPoint.xsd, XMLInstances/ExtInterfaces/SGr_02_0017_xxxx_HOVAL_HeatPump_V0.1.1.xml, XMLInstances/ExtInterfaces/SGr_02_0033_0000_CTA_HeatPump_V0.1.1.xml, XMLInstances/ExtInterfaces/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPumpV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPumpV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V0.5.1.xml, XMLInstances/FuncProfiles/FP_0_0016_40_4_0.2_EnergyMonitor.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_BufferStorageCtrl_m_0.5.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_EnergyMonitor_2_0.3.xml, XMLInstances/FuncProfiles/FP_SGr_HeatPumpControl_EnergyMonitor_m_0.5.xml, XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/GenericAttributes.xsl, XMLInstances/xsl/Helpers.xsl, XMLInstances/xsl/TransportServiceModbus.xsl
=> #256 Finalization of Heatpumps

SchemaDatabase/SGr/Product/RestApiTypes.xsd, XMLInstances/ExtInterfaces/SGr_02_0018_CLEMAP_EIcloudEnergyMonitor_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_02_0034_0053_Lehmann_SCC_v1.0.0.xml, XMLInstances/ExtInterfaces/SGr_02_mmmm_dddd_MEO_EI_Propilot_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_CLEMAPEnergyMonitorEIV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_GroupeE_V0.0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_V0.0.1.xml, XMLInstances/FuncProfiles/FP_SGr_Actuator_Relais_2m_0.1.xml
- Separates query parameters from request path
- separate requestForm data structure when using form data instead of body
- adapted existing EIDs
=> REST query and form parameters

XMLInstances/xsl/TransportServiceRestApi.xsl
Update XSL for change in XSD for RestAPI
=> #298 Update XSL for change in XSD for RestAPI

XMLInstances/ExtInterfaces/SGr_02_0015_xxxx_StiebelEltron_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_02_0017_xxxx_HOVAL_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V0.5.1.xml
=> #265 Finalization of Heatpumps

XMLInstances/FuncProfiles/FP_SGr_SGCP_LoadManagement_2_0.1.xml
=> #299 SGCP Load Reduction

XMLInstances/FuncProfiles/FP_SGr_SGCP_LoadManagement_2_0.1.xml
publish functional Profiles for Heatpumps
=> #265 publish functional Profiles for Heatpumps

XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V0.5.1.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V1.0.0.xml
=> #265 Typo in Heatpump HOVAL EID

XMLInstances/ExtInterfaces/EI4_UniDirFlexFeedIn_3632Lv2.xml, XMLInstances/ExtInterfaces/EI4_UniDirFlexLoad_3631Lv2.xml
changed value to match data type. otherwise EID cannot be loaded.
=> changed value to match data type.

doc/functionalProfile.md, doc/product.md
=> Documemt EID File Names

XMLInstances/FuncProfiles/FP_SGr_SGCP_FlexLoadMgmt_3_0.1.xml
=> Draft for Vivavis SGCP

SchemaDatabase/SGr/Generic/BaseTypes.xsd
=> Fix unsignedIntParameter

XMLInstances/xsl/DataPoint.xsl
Correct Table Header for Datapoint
=> Correct Table Header for Datapoint

XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_GroupeE_V0.0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_V0.0.1.xml, XMLInstances/FuncProfiles/FP_SGr_Dynamic_Tariff_0.1.xml
=> Cleanup Dynamic Tariffs

XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPumpV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V1.0.0.xml, XMLInstances/FuncProfiles/FP_SGr_DeviceInformation_DeviceInformation_m_0.1.xml
Device Information with Device ID
=> Device Information with Device ID

XMLInstances/FuncProfiles/FP_SGr_SGCP_FlexLoadMgmt_4m.0.2.xml, XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/Helpers.xsl, XMLInstances/xsl/TransportServiceModbus.xsl
=> FP VIVAVIS SolarManager

XMLInstances/ExtInterfaces/SGr_02_0003_0055_eCarupPICO_4061_v1.0.0.xml
=> Fix Manufacturer Name

XMLInstances/ExtInterfaces/SGr_02_0017_xxxx_HOVAL_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_02_0033_0000_CTA_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_0017_xxxx_HOVAL_HeatPump_V1.0.0.xml, XMLInstances/ExtInterfaces/SGr_04_0020_xxxx_Heliotherm_HeatPumpV0.2.1.xml, XMLInstances/ExtInterfaces/SGr_04_0033_0000_CTA_HeatPump_V1.0.0.xml
placeholder must match configurationList element!
=> fixed inconsistent configuration parameters

XMLInstances/ExtInterfaces/SGr_00_mmmm_dddd_Shelly_Pro3EM_RestAPILocalBasicAuth_V1.0.xml, XMLInstances/ExtInterfaces/SGr_00_mmmm_dddd_Shelly_Pro3EM_RestAPILocalNoAuth_V1.0.xml
Display unique device name in library
=> Distinguish local API variants of Shelly Pro 3EM.

XMLInstances/ExtInterfaces/SGr_00_mmmm_dddd_Ensor_Blue2Box_ModbusTCP_Opt_V1.0.xml
- final changes requested by Ensor
- verified in Testlab
- set state to Published
=> Publish Ensor Blue2Box V1.0.0

XMLInstances/FuncProfiles/FP_SGr_SGCP_FlexMgmt_4m.0.5.xml
Vivavis Flex Management Pilote
=> Vivavis Flex Management Pilote

XMLInstances/ExtInterfaces/SGr_04_0020_xxxx_Heliotherm_HeatPumpV0.2.1.xml
Applied corrections based on manufacturer documentation and verified in test lab.
**please squash**
=> Fixed Heliotherm EID

XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_SolarManager_FlexMgmt_BasicAuth_V0.1.xml, XMLInstances/ExtInterfaces/SGr_04_mmmm_dddd_SolarManager_FlexMgmt_OAuth_V0.1.xml
Contains demo EIDs for the FP `FlexMgmt`, using SolarManager cloud API.
**please squash**
=> Demo Project - Solarmanager Flex-Management

SchemaDatabase/SGr/Product/MessagingTypes.xsd
Optional value mapping for messaging data points, like in REST API
=> Optional value mapping for messaging data points

XMLInstances/ExtInterfaces/SGr_02_mmmm_8288089799_Smart-me_SubMeterElectricity_V1.1.0.xml
only minor corrections and default config values
=> bugfixes for smart-me meter

XMLInstances/FuncProfiles/FP_SGr_Actuator_Relais_1m_0.1.xml, XMLInstances/FuncProfiles/FP_SGr_Actuator_Relais_1m_1.0.xml
please merge after approval from "Deklarationsstelle"
=> Corrected level of operation and description of FP Actuator:Relais

XMLInstances/FuncProfiles/FP_SGr_SGCP_LoadManagement_2m_0.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2_1.0.xml
=> SGCP Consolidation

XMLInstances/FuncProfiles/FP_SGr_Actuator_Relais_1m_0.1.xml, XMLInstances/FuncProfiles/FP_SGr_Actuator_Relais_1m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_DeviceInformation_DeviceInformation_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_ApparentEnergyAC_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_ApparentPowerAC_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_PowerFactor_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_ReactiveEnergyAC_m_1.0.xml, XMLInstances/FuncProfiles/FP_SGr_Metering_VoltageAC_m_1.0.xml
Created V1.0 of various "standard" metering FPs, which have no official version yet.
Is ready for review (technically), but I am still waiting for the confirmation from _Deklarationsstelle_
=> Version 1.0 of standard metering FPs

XMLInstances/FuncProfiles/FP_SGr_SGCP_FlexMgmt_2_0.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_FlexMgmt_2m_0.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_FlexMgmt_4m.0.5.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2_2.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexFeedInMgmt_2m_2.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2_2.0.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_UniDirFlexLoadMgmt_2m_2.0.xml
- Renamed FP type
- Renamed data points
- created new version of UniDir FPs due to data point change
=> SGCP FlexMgmt

XMLInstances/ExtInterfaces/SGr_04_0018_CLEMAP_LoadManagement_ModbusTCP_V1.0.xml, XMLInstances/ExtInterfaces/SGr_04_0018_CLEMAP_LoadManagement_RestAPILocal_V1.0.xml
requested by Gino.
old EIDs have been manually deleted from library.
=> Renamed CLEMAP EIDs meant for load management

XMLInstances/xsl/DataPoint.xsl, XMLInstances/xsl/DeviceFrame.xsl, XMLInstances/xsl/FunctionalProfile.xsl, XMLInstances/xsl/FunctionalProfileFrame.xsl, XMLInstances/xsl/GenericAttributes.xsl, XMLInstances/xsl/Helpers.xsl, XMLInstances/xsl/SGr.css, XMLInstances/xsl/SGr.xsl, XMLInstances/xsl/TransportServiceContactApi.xsl, XMLInstances/xsl/TransportServiceMessaging.xsl, XMLInstances/xsl/TransportServiceModbus.xsl, XMLInstances/xsl/TransportServiceRestApi.xsl
- Links now contain the actual link target defined by the URI
- corrected indentation of XSL files
=> Fixed URI link rendering in XSL

SchemaDatabase/SGr/Generic/BaseTypes.xsd, XMLInstances/FuncProfiles/FP_SGr_SGCP_FeedInCurtailment_4m_0.1.xml, XMLInstances/FuncProfiles/FP_SGr_SGCP_FeedInCurtailment_4m_1.0.xml
- added final version of FP
- specification requires unit `W/m2`
a patch release of the specification packages will be published after merging this PR.
=> Publish SGCP FeedInCurtailment

XMLInstances/FuncProfiles/FP_SGr_SGCP_FeedInCurtailment_4m_1.0.xml
Minimal text correction, requested by SGCP group
=> SGCP FeedInCurtailment Correction

XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_EKZ_V0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_V1.0.xml
plus minor modification of other tariffs
=> Draft of EKZ dynamic tariff

XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_AEM_V0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_CKW_V0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_EKZ_V0.1.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_GroupeE_V1.0.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_Test_V1.0.xml, XMLInstances/ExtInterfaces/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_V1.0.xml
- set _integrated_ as default tariff type, as discussed
- added draft for production API of ESIT/Swisspower
=> Dyn tariff updates
